### ISSUE TITLE
App Connector Module - Add Compass Runtime Agent to the module

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/application-connector-manager#53] opened 2023-10-03 14:57 UTC
**Description**
The module must contain the Compass Runtime Agent

**Acceptance criteria**
- [ ] Application Connector Module contains the Compass Runtime Agent
- [ ] The Compass Runtime Agent's deployment is scaled to zero when the secret with the configuration doesn't exist

**Comment by koala7659** [comment] 2023-10-18 16:38
Duplicate of https://github.com/kyma-project/application-connector-manager/issues/48

**Comment by tobiscr** [comment] 2023-12-15 17:36
@koala7659  - Can. we close this one as duplicate of #48 ?

**Comment by tobiscr** [comment] 2023-12-18 14:56
Moved ACs of this issue to #48 and closing it as duplicate

**Closed by tobiscr** 2023-12-18 14:56 UTC
