### ISSUE TITLE
Enable Markdown link check to find any broken links

### ISSUE THREAD

**Issue by grego952** [kyma-project/application-connector-manager#106] opened 2023-11-13 14:31 UTC
**Description**
The /kyma-project repositories in GitHub should use [Markdown link check](https://github.com/tcort/markdown-link-check) to check their Markdown files for broken links. 
We should configure this tool for the Application Connector Manager repo.

**Reasons**
It facilitates checking for broken links.

**Attachments**

**Comment by Disper** [comment] 2023-11-13 15:01
Is it a duplicate of https://github.com/kyma-project/application-connector-manager/issues/42 ?

**Closed** 2023-11-15 17:33 UTC
Labels: area/application-connector
