### ISSUE TITLE
App Connector Module - Include Compass Runtime Agent into application-connector module

### ISSUE THREAD

**Issue by koala7659** [kyma-project/application-connector-manager#27] opened 2023-08-23 11:05 UTC
Include all charts of Compass Runtime Agent into yaml file of the application-connector Kyma module .

**Acceptance criteria**

- [x] Compass Runtime Agent should be running without errors as part of application-connector module.

**Comment by akgalwas** [comment] 2023-08-23 12:21
Pick one of the following solutions:
- Only if secret with token is not available the Compass Runtime Agent yaml should be installed.
- CRA is installed no matter if the secret exists (make sure the CRA will connect to Compass once secret is created)

**Comment by akgalwas** [comment] 2023-08-23 12:23
Mind how CRA is integrated with Compass Runtime Agent.

**Comment by koala7659** [comment] 2023-08-29 07:24
PR: https://github.com/kyma-project/application-connector-manager/pull/28/files

**Comment by tobiscr** [comment] 2023-12-19 07:51
@koala7659  - Isn't this a duplicate of #48 ?

**Comment by koala7659** [comment] 2024-03-04 13:43
@tobiscr Yes, indeed!

**Closed** 2024-03-25 12:21 UTC
Labels: area/application-connector, bv/maintainability
